import type { AdminUserItem } from '@/types/api/admin';

export const MOCK_ADMIN_USERS: AdminUserItem[] = [
  {
    userId: 1,
    name: '김민수',
    email: 'minsu.kim@kookmin.ac.kr',
    userType: 'student',
    role: 'user',
    dailyChatLimit: 30,
    usedToday: 15,
  },
  {
    userId: 2,
    name: '이서연',
    email: 'seoyeon.lee@kookmin.ac.kr',
    userType: 'student',
    role: 'user',
    dailyChatLimit: 30,
    usedToday: 28,
  },
  {
    userId: 3,
    name: '박지훈',
    email: 'jihoon.park@kookmin.ac.kr',
    userType: 'student',
    role: 'user',
    dailyChatLimit: 30,
    usedToday: 30,
  },
  {
    userId: 4,
    name: '정하은',
    email: 'haeun.jung@kookmin.ac.kr',
    userType: 'student',
    role: 'admin',
    dailyChatLimit: 50,
    usedToday: 5,
  },
  {
    userId: 5,
    name: '최영호',
    email: 'youngho.choi@kookmin.ac.kr',
    userType: 'staff',
    role: 'user',
    dailyChatLimit: 50,
    usedToday: 0,
  },
  {
    userId: 6,
    name: '강수진',
    email: 'sujin.kang@kookmin.ac.kr',
    userType: 'staff',
    role: 'admin',
    dailyChatLimit: 50,
    usedToday: 12,
  },
  {
    userId: 7,
    name: '윤재현',
    email: 'jaehyun.yoon@kookmin.ac.kr',
    userType: 'student',
    role: 'user',
    dailyChatLimit: 20,
    usedToday: 0,
  },
  {
    userId: 8,
    name: '한소희',
    email: 'sohee.han@kookmin.ac.kr',
    userType: 'staff',
    role: 'user',
    dailyChatLimit: 30,
    usedToday: 5,
  },
  {
    userId: 9,
    name: '오준서',
    email: 'junseo.oh@kookmin.ac.kr',
    userType: 'student',
    role: 'user',
    dailyChatLimit: 20,
    usedToday: 18,
  },
  {
    userId: 10,
    name: '임도윤',
    email: 'doyoon.lim@kookmin.ac.kr',
    userType: 'staff',
    role: 'admin',
    dailyChatLimit: 50,
    usedToday: 45,
  },
];

export const MOCK_DEFAULT_CHAT_LIMIT = 30;
