// TODO: 실제 API 연동 시 제거

import type {
  Document,
  CategoryNode,
  PopularDocument,
} from "@/types/api/document";

export const MOCK_DOCUMENTS: Document[] = [
  {
    documentId: "1",
    title: "AWS 클라우드 특강 안내 (3/25)",
    category: "SW 특강 및 행사",
    categoryPath: "SW 특강 및 행사",
    department: "SW학부 행사팀",
    updatedAt: "2026-03-15",
    fileSize: "PDF · 0.3MB",
    viewCount: 178,
    excerpt: "AWS 클라우드 서비스 활용 방법에 대한 특강이 3월 25일에 개최됩니다. 재학생 누구나 참여 가능합니다.",
    refCount: 12,
  },
  {
    documentId: "2",
    title: "2026 창업아이디어 경진대회 안내",
    category: "SW 특강 및 행사",
    categoryPath: "국민대학교 공지 > 특강공지",
    department: "산학협력단",
    updatedAt: "2026-03-12",
    fileSize: "PDF · 1.0MB",
    viewCount: 189,
    excerpt: "2026년 창업아이디어 경진대회 참가자를 모집합니다. 팀 단위 참가 가능하며 우수팀에게는 창업 지원금이 제공됩니다.",
    refCount: 8,
  },
  {
    documentId: "3",
    title: "2026 SW융합대학 해커톤 참가자 모집",
    category: "SW 특강 및 행사",
    categoryPath: "SW 특강 및 행사",
    department: "SW학부 행사팀",
    updatedAt: "2026-03-05",
    fileSize: "PDF · 1.5MB",
    viewCount: 345,
    excerpt: "SW융합대학 주관 해커톤 행사 참가자를 모집합니다. 24시간 동안 진행되는 개발 경진대회입니다.",
    refCount: 21,
  },
  {
    documentId: "4",
    title: "2026-1학기 SW학부 성적우수 장학금 안내",
    category: "SW 장학공지",
    categoryPath: "SW 장학공지",
    department: "SW학부 교학팀",
    updatedAt: "2026-03-05",
    fileSize: "PDF · 0.4MB",
    viewCount: 534,
    excerpt: "2026년 1학기 SW학부 성적우수 장학금 신청 대상 및 신청 방법을 안내합니다.",
    refCount: 35,
  },
  {
    documentId: "5",
    title: "2026년 상반기 삼성전자 채용연계형 인턴 모집",
    category: "SW 취업공지",
    categoryPath: "SW 취업공지",
    department: "SW취업지원센터",
    updatedAt: "2026-03-01",
    fileSize: "PDF · 1.2MB",
    viewCount: 723,
    excerpt: "삼성전자 2026년 상반기 채용연계형 인턴십 모집 공고입니다. SW 관련 전공자 우대.",
    refCount: 45,
  },
  {
    documentId: "6",
    title: "2026년 학생증 재발급 안내",
    category: "SW 학사공지",
    categoryPath: "국민대학교 공지 > 행정공지",
    department: "총무처",
    updatedAt: "2026-03-01",
    fileSize: "PDF · 0.2MB",
    viewCount: 234,
    excerpt: "학생증 분실 또는 훼손 시 재발급 절차와 준비 서류를 안내합니다.",
    refCount: 5,
  },
  {
    documentId: "7",
    title: "SW중심대학 장학금 신청 안내",
    category: "SW 장학공지",
    categoryPath: "SW 장학공지",
    department: "SW학부 교학팀",
    updatedAt: "2026-02-25",
    fileSize: "PDF · 0.5MB",
    viewCount: 389,
    excerpt: "SW중심대학 사업 관련 장학금 신청 자격, 금액, 신청 방법 등을 안내합니다.",
    refCount: 28,
  },
  {
    documentId: "8",
    title: "네이버 부스트캠프 9기 모집",
    category: "SW 취업공지",
    categoryPath: "SW 취업공지",
    department: "SW취업지원센터",
    updatedAt: "2026-02-20",
    fileSize: "PDF · 0.6MB",
    viewCount: 456,
    excerpt: "네이버 부스트캠프 AI Tech 9기 및 Web 9기 교육생을 모집합니다.",
    refCount: 32,
  },
  {
    documentId: "9",
    title: "재수강 신청 안내 (2026-1학기)",
    category: "SW 학사공지",
    categoryPath: "SW 학사공지",
    department: "SW학부 교학팀",
    updatedAt: "2026-02-15",
    fileSize: "PDF · 0.3MB",
    viewCount: 234,
    excerpt: "2026-1학기 재수강 신청 기간, 대상, 방법에 대해 안내합니다.",
    refCount: 15,
  },
  {
    documentId: "10",
    title: "2026학년도 교내 근로장학생 모집",
    category: "SW 장학공지",
    categoryPath: "국민대학교 공지 > 교내채용",
    department: "학생지원처",
    updatedAt: "2026-02-15",
    fileSize: "PDF · 0.4MB",
    viewCount: 567,
    excerpt: "2026학년도 1학기 교내 근로장학생 모집 공고입니다. 모집 부서 및 신청 방법을 확인하세요.",
    refCount: 18,
  },
  {
    documentId: "11",
    title: "2026학년도 1학기 등록금 납부 안내",
    category: "SW 학사공지",
    categoryPath: "국민대학교 공지 > 학사공지",
    department: "교무처",
    updatedAt: "2026-02-01",
    fileSize: "PDF · 0.7MB",
    viewCount: 2341,
    excerpt: "2026학년도 1학기 등록금 납부 기간 및 방법, 분할납부 제도에 대해 안내합니다.",
    refCount: 87,
  },
  {
    documentId: "12",
    title: "국민대학교 학칙 전문 (2026년 개정)",
    category: "SW 학사공지",
    categoryPath: "국민대학교 공지 > 학사공지",
    department: "교무처",
    updatedAt: "2025-12-20",
    fileSize: "PDF · 5.1MB",
    viewCount: 3456,
    excerpt: "2026년 개정된 국민대학교 학칙 전문입니다. 주요 개정 사항은 수강 규정 및 졸업 요건 변경입니다.",
    refCount: 142,
  },
  {
    documentId: "13",
    title: "2026학년도 학사일정 공고",
    category: "SW 학사공지",
    categoryPath: "국민대학교 공지 > 학사공지",
    department: "교무처",
    updatedAt: "2026-01-02",
    fileSize: "PDF · 0.9MB",
    viewCount: 4521,
    excerpt: "2026학년도 전체 학사일정을 공고합니다. 수강신청, 중간·기말고사, 방학 일정 등을 확인하세요.",
    refCount: 203,
  },
  {
    documentId: "14",
    title: "2026-1학기 국가장학금 신청 안내",
    category: "SW 장학공지",
    categoryPath: "국민대학교 공지 > 장학공지",
    department: "학생지원처",
    updatedAt: "2026-01-20",
    fileSize: "PDF · 0.4MB",
    viewCount: 1890,
    excerpt: "2026-1학기 국가장학금(I·II 유형) 신청 일정 및 방법을 안내합니다.",
    refCount: 76,
  },
  {
    documentId: "15",
    title: "2026-1학기 사회봉사 교과목 안내",
    category: "SW 학사공지",
    categoryPath: "국민대학교 공지 > 학사공지",
    department: "교무처",
    updatedAt: "2026-02-10",
    fileSize: "PDF · 0.3MB",
    viewCount: 189,
    excerpt: "2026-1학기 사회봉사 교과목 수강 신청 방법과 인정 시간 기준을 안내합니다.",
    refCount: 9,
  },
  {
    documentId: "16",
    title: "복수전공 신청 안내 (2026학년도)",
    category: "SW 학사공지",
    categoryPath: "SW 학사공지",
    department: "SW학부 교학팀",
    updatedAt: "2026-02-05",
    fileSize: "PDF · 0.5MB",
    viewCount: 678,
    excerpt: "2026학년도 복수전공 신청 기간, 자격 요건, 신청 방법에 대해 안내합니다.",
    refCount: 41,
  },
  {
    documentId: "17",
    title: "졸업요건 확인 안내",
    category: "SW 졸업요건",
    categoryPath: "SW 졸업요건",
    department: "SW학부 교학팀",
    updatedAt: "2026-01-15",
    fileSize: "PDF · 0.6MB",
    viewCount: 2123,
    excerpt: "SW학부 졸업요건 확인 방법 및 졸업심사 신청 절차를 안내합니다.",
    refCount: 98,
  },
  {
    documentId: "18",
    title: "현장실습 학점 인정 기준",
    category: "SW 취업공지",
    categoryPath: "SW 취업공지",
    department: "SW취업지원센터",
    updatedAt: "2025-12-15",
    fileSize: "PDF · 0.4MB",
    viewCount: 345,
    excerpt: "현장실습 이수 시 학점 인정 기준 및 신청 절차를 안내합니다.",
    refCount: 27,
  },
  {
    documentId: "19",
    title: "학사경고 및 제적 기준 안내",
    category: "SW 학사공지",
    categoryPath: "국민대학교 공지 > 학사공지",
    department: "교무처",
    updatedAt: "2025-12-20",
    fileSize: "PDF · 0.3MB",
    viewCount: 567,
    excerpt: "학사경고 기준, 제적 절차, 재입학 방법에 대해 안내합니다.",
    refCount: 33,
  },
  {
    documentId: "20",
    title: "SW융합대학 교육과정표 (2026학년도)",
    category: "SW 학사공지",
    categoryPath: "SW 학사공지",
    department: "SW학부 교학팀",
    updatedAt: "2026-02-25",
    fileSize: "PDF · 1.5MB",
    viewCount: 890,
    excerpt: "2026학년도 SW융합대학 전체 교육과정표입니다. 전공 필수·선택, 교양 이수 기준을 확인하세요.",
    refCount: 55,
  },
  {
    documentId: "21",
    title: "캡스톤디자인 과목 안내",
    category: "SW 학사공지",
    categoryPath: "SW 학사공지",
    department: "SW학부 교학팀",
    updatedAt: "2026-03-10",
    fileSize: "PDF · 0.7MB",
    viewCount: 456,
    excerpt: "캡스톤디자인 수강 신청 방법, 팀 구성, 발표 일정에 대해 안내합니다.",
    refCount: 30,
  },
];

export const MOCK_CATEGORY_TREE: CategoryNode[] = [
  {
    categoryId: "sw-academic",
    name: "SW 학사공지",
    documentCount: 4,
  },
  {
    categoryId: "sw-career",
    name: "SW 취업공지",
    documentCount: 2,
  },
  {
    categoryId: "sw-scholarship",
    name: "SW 장학공지",
    documentCount: 2,
  },
  {
    categoryId: "sw-event",
    name: "SW 특강 및 행사",
    documentCount: 2,
  },
  {
    categoryId: "sw-graduation",
    name: "SW 졸업요건",
    documentCount: 2,
  },
  {
    categoryId: "kmu",
    name: "국민대학교 공지",
    documentCount: 9,
    children: [
      { categoryId: "kmu-academic", name: "학사공지", documentCount: 3 },
      { categoryId: "kmu-admin", name: "행정공지", documentCount: 1 },
      { categoryId: "kmu-recruit", name: "교내채용", documentCount: 1 },
      { categoryId: "kmu-event", name: "특강공지", documentCount: 1 },
      { categoryId: "kmu-scholarship", name: "장학공지", documentCount: 2 },
      { categoryId: "kmu-volunteer", name: "사회봉사", documentCount: 1 },
    ],
  },
];

export const MOCK_POPULAR_DOCUMENTS: PopularDocument[] = [
  {
    documentId: "13",
    title: "2026학년도 학사일정 공고",
    category: "SW 학사공지",
    viewCount: 4521,
    updatedAt: "2026-01-02T00:00:00Z",
  },
  {
    documentId: "12",
    title: "국민대학교 학칙 전문 (2026년 개정)",
    category: "SW 학사공지",
    viewCount: 3456,
    updatedAt: "2025-12-20T00:00:00Z",
  },
  {
    documentId: "11",
    title: "2026학년도 1학기 등록금 납부 안내",
    category: "SW 학사공지",
    viewCount: 2341,
    updatedAt: "2026-02-01T00:00:00Z",
  },
  {
    documentId: "17",
    title: "졸업요건 확인 안내",
    category: "SW 졸업요건",
    viewCount: 2123,
    updatedAt: "2026-01-15T00:00:00Z",
  },
  {
    documentId: "14",
    title: "2026-1학기 국가장학금 신청 안내",
    category: "SW 장학공지",
    viewCount: 1890,
    updatedAt: "2026-01-20T00:00:00Z",
  },
];
